name: Build & Publish Backend
on:
  push:
    branches: [ master ]
    paths:
      - 'services/backend/**'
      - 'Cargo.*'
      - '.github/workflows/build-publish-backend.yml'

jobs:
  backend:
    name: Build & publish backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Login to Google Artifacts Registry
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev/
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: services/backend/Dockerfile
          push: true
          tags: us-docker.pkg.dev/yew-rs/yew-playground/playground:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'playground-backend'
          region: us-west1
          image: us-docker.pkg.dev/yew-rs/yew-playground/playground:latest

      - name: Deploy URL
        run: echo ${{ steps.deploy.outputs.url }}
