name: Build & Publish App and Compiler
on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
      - 'services/app-compiler/**'
      - 'Cargo.*'
      - '.github/workflows/build-publish-app-compiler.yml'

jobs:
  app:
    name: Build and publish app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Login to Google Artifacts Registry
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev/
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: app
          push: true
          tags: us-docker.pkg.dev/yew-rs/yew-playground/app:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  compiler:
    name: Build & publish app compiler
    runs-on: ubuntu-latest
    needs:
      - app
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Login to Google Artifacts Registry
        uses: docker/login-action@v1
        with:
          registry: us-docker.pkg.dev/
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: services/app-compiler/Dockerfile
          push: true
          tags: us-docker.pkg.dev/yew-rs/yew-playground/playground-compiler:latest

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'playground-compiler'
          region: us-west1
          image: us-docker.pkg.dev/yew-rs/yew-playground/playground-compiler:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy URL
        run: echo ${{ steps.deploy.outputs.url }}
